tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "jq"
brew "ansiweather"
brew "autoenv"
brew "autojump"
brew "awk"
brew "ghc"
brew "cabal-install"
brew "sqlite"
brew "cmake"
brew "coreutils"
brew "ctags"
brew "diff-so-fancy"
brew "emojify"
brew "icu4c"
brew "ffmpeg"
brew "fontforge", link: false
brew "gdb"
brew "ghostscript"
brew "gnupg"
brew "gnuplot"
brew "go"
brew "haskell-stack"
brew "llvm"
brew "mas"
brew "mpv"
brew "neofetch"
brew "neovim"
brew "nmap"
brew "node"
brew "peco"
brew "pinentry-mac"
brew "pipenv"
brew "pyenv"
brew "pyenv-virtualenv"
brew "ruby"
brew "screenfetch", args: ["HEAD"]
brew "sourcekitten"
brew "swiftlint"
brew "telnet"
brew "thefuck"
brew "tmux"
brew "tree"
brew "wget"
brew "yarn"
brew "you-get"
brew "zlib"
brew "zplug"
brew "zsh"
cask "1password"
cask "adobe-acrobat-reader"
cask "adobe-creative-cloud"
cask "alfred"
cask "arduino"
cask "balenaetcher"
cask "bartender"
cask "chromedriver"
cask "daisydisk"
cask "dash"
cask "detexify"
cask "dropbox"
cask "duet"
cask "endurance"
cask "evernote"
cask "firefox"
cask "font-hack-nerd-font"
cask "font-nanumgothiccoding"
cask "font-nanummyeongjo"
cask "font-noto-sans"
cask "font-noto-sans-cjk"
cask "font-noto-sans-cjk-kr"
cask "font-noto-sans-mono"
cask "font-noto-serif"
cask "font-noto-serif-cjk"
cask "font-noto-serif-cjk-kr"
cask "font-tex-gyre-pagella"
cask "font-tex-gyre-pagella-math"
cask "font-ubuntumono-nerd-font-mono"
cask "fontforge"
cask "freedom"
cask "gitkraken"
cask "go2shell"
cask "google-chrome"
cask "gpg-suite"
cask "insomnia"
cask "istat-menus"
cask "iterm2"
cask "jetbrains-toolbox"
cask "keka"
cask "lepton"
cask "mactex"
cask "mathpix-snipping-tool"
cask "mounty"
cask "mpv"
cask "notion"
cask "omnifocus"
cask "papers"
cask "pdf-expert"
cask "r"
cask "realm-studio"
cask "rstudio"
cask "sketch"
cask "skim"
cask "skype"
cask "slack"
cask "spectacle"
cask "sublime-text"
cask "the-unarchiver"
cask "transmission"
cask "typora"
cask "vlc"
cask "vnc-server"
cask "vnc-viewer"
cask "xquartz"
cask "yemuzip"
cask "zeplin"
mas "AdBlock", id: 1402042596
mas "Be Focused", id: 973134470
mas "Cascadea", id: 1432182561
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "iStudiez Pro", id: 402989379
mas "Keynote", id: 409183694
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "MindNode", id: 1289197285
mas "Notability", id: 736189492
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Scopie", id: 1027457763
mas "Xcode", id: 497799835
mas "카카오톡", id: 869223134
